-- Examples

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE ORDERS (
    ID INTEGER IDENTITY PRIMARY KEY,
    CUSTOMER_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL
);

CREATE TABLE "USERS" (
    "USER_ID" IDENTITY NOT NULL PRIMARY KEY,
    "USERNAME" VARCHAR(40) NOT NULL,
    "EMAIL" VARCHAR(35) NOT NULL,
    "PASSWORD" VARCHAR(512) NOT NULL
);